# Generated by Django 5.2.5 on 2025-09-16 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('boss', 'Boshliq (Ega)'), ('finance', 'Moliyachi'), ('seller', 'Sotuvchi')], default='seller', max_length=10, verbose_name='Rol')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqami')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
