# Generated by Django 5.2.5 on 2025-09-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accessory_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Aksessuar komissiya foizi (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Asosiy maosh ($)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exchange_commission_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Almashtirish komissiya foizi (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_commission_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Telefon komissiya foizi (%)'),
        ),
    ]
