# Generated by Django 5.2.5 on 2025-09-29 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_accessory_commission_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accessory_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Aksessuar foydasi foizi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exchange_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Almashtirish foydasi foizi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Telefon foydasi foizi (%)'),
        ),
    ]
