# Generated by Django 5.2.5 on 2025-09-29 15:58

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi profili', 'verbose_name_plural': 'Foydalanuvchi profillari'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accessory_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Aksessuar foydasi foizi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exchange_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Almashtirish foydasi foizi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Telefon foydasi foizi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('boss', 'Boshliq (Ega)'), ('finance', 'Moliyachi'), ('seller', 'Sotuvchi')], default='seller', max_length=10, verbose_name='Rol'),
        ),
    ]
