# Generated by Django 5.2.5 on 2025-09-29 16:01

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='base_salary',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_salary_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dollar hisobida', max_digits=10, verbose_name='Asosiy maosh (USD)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='base_salary_uzs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="So'm hisobida", max_digits=15, verbose_name='Asosiy maosh (UZS)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accessory_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Aksessuar foydasi foizi (So'm)", max_digits=5, verbose_name='Aksessuar komissiyasi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exchange_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Almashtirish foydasi foizi (Dollar)', max_digits=5, verbose_name='Almashtirish komissiyasi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Telefon foydasi foizi (Dollar)', max_digits=5, verbose_name='Telefon komissiyasi (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('boss', 'Rahbar'), ('finance', 'Moliyachi'), ('seller', 'Sotuvchi')], default='seller', max_length=10, verbose_name='Rol'),
        ),
    ]
