# Generated by Django 5.2.5 on 2025-10-02 07:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Telefon komissiya (%)')),
                ('accessory_commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aksessuar komissiya (%)')),
                ('exchange_commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Almashtirish komissiya (%)')),
                ('base_salary_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Asosiy maosh (USD)')),
                ('base_salary_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Asosiy maosh (UZS)')),
                ('effective_date', models.DateField(db_index=True, verbose_name='Amal qilish sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_changes', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komissiya tarixi',
                'verbose_name_plural': 'Komissiya tarixlari',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['user', 'effective_date'], name='users_commi_user_id_ddc187_idx')],
            },
        ),
    ]
