# Generated by Django 5.2.5 on 2025-10-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_commissionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('boss', 'Rahbar'), ('finance', 'Moliyachi'), ('seller', 'Sotuvchi'), ('operator', 'Operator')], default='seller', max_length=10, verbose_name='Rol'),
        ),
    ]
