# Generated by Django 5.2.5 on 2025-09-16 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Usta',
                'verbose_name_plural': 'Ustalar',
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Xizmat haqi')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'langan summa")),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Tugallangan')], default='in_progress', max_length=15, verbose_name='Holati')),
                ('repair_reasons', models.TextField(verbose_name="Ta'mirlash sabablari")),
                ('given_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ustaga berilgan sana')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Qaytarish rejalashtirilgan sana')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('debt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_service', to='sales.debt', verbose_name="Bog'langan qarz")),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='services.master', verbose_name='Usta')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='inventory.phone', verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Usta xizmati',
                'verbose_name_plural': 'Usta xizmatlari',
            },
        ),
        migrations.CreateModel(
            name='MasterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="To'lov summasi")),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="To'lovchi")),
                ('master_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.masterservice', verbose_name='Usta xizmati')),
            ],
            options={
                'verbose_name': "Usta to'lovi",
                'verbose_name_plural': "Usta to'lovlari",
            },
        ),
    ]
