# Generated by Django 5.2.5 on 2025-09-19 14:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterpayment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': "Usta to'lovi", 'verbose_name_plural': "Usta to'lovlari"},
        ),
        migrations.AlterModelOptions(
            name='masterservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usta xizmati', 'verbose_name_plural': 'Usta xizmatlari'},
        ),
        migrations.AddField(
            model_name='masterpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="To'lov summasi"),
        ),
        migrations.AddField(
            model_name='masterpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt'),
            preserve_default=False,
        ),
    ]
