# Generated by Django 5.2.5 on 2025-09-19 17:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_masterpayment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpayment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='debt',
        ),
        migrations.AlterField(
            model_name='masterpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="To'lov summasi"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterpayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="To'lovchi"),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
    ]
