# Generated by Django 5.2.5 on 2025-09-19 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_phoneexchange_customer_alter_phonesale_phone'),
        ('services', '0003_remove_masterpayment_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterservice',
            name='debt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_service', to='sales.debt', verbose_name="Bog'langan qarz"),
        ),
        migrations.AlterField(
            model_name='masterpayment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="To'lovchi"),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
    ]
