# Generated by Django 5.2.5 on 2025-09-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_master_email_masterservice_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='email',
        ),
    ]
