# Generated by Django 5.2.5 on 2025-09-22 01:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_phone_client_name_and_more'),
        ('sales', '0008_alter_phoneexchange_old_phone_evaluated_price'),
        ('services', '0006_remove_master_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Usta', 'verbose_name_plural': 'Ustalar'},
        ),
        migrations.AlterField(
            model_name='masterpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='masterpayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="To'lovchi"),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Xizmat haqi'),
        ),
        migrations.AddIndex(
            model_name='masterpayment',
            index=models.Index(fields=['master_service', 'payment_date'], name='services_ma_master__8cda4c_idx'),
        ),
        migrations.AddIndex(
            model_name='masterpayment',
            index=models.Index(fields=['payment_date'], name='services_ma_payment_0ea7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='masterservice',
            index=models.Index(fields=['status', 'master'], name='services_ma_status_87eaee_idx'),
        ),
        migrations.AddIndex(
            model_name='masterservice',
            index=models.Index(fields=['status', 'created_at'], name='services_ma_status_13ed71_idx'),
        ),
        migrations.AddIndex(
            model_name='masterservice',
            index=models.Index(fields=['phone', 'status'], name='services_ma_phone_i_26eba0_idx'),
        ),
    ]
