# Generated by Django 5.2.5 on 2025-09-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_master_options_alter_masterpayment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(blank=True, help_text="boss_to_master qarz yaratish uchun ustani User bilan bog'lang", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name="Bog'langan foydalanuvchi"),
        ),
    ]
