# Generated by Django 5.2.5 on 2025-09-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_master_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='user',
        ),
        migrations.RemoveField(
            model_name='masterservice',
            name='debt',
        ),
    ]
