# Generated by Django 5.2.5 on 2025-10-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_master_user_remove_masterservice_debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterservice',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_services', to=settings.AUTH_USER_MODEL, verbose_name='Tugallagan foydalanuvchi'),
        ),
    ]
