# Generated by Django 5.2.5 on 2025-09-16 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True, verbose_name='Xotira hajmi')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xotira hajmi',
                'verbose_name_plural': 'Xotira hajmlari',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, unique=True, verbose_name='iPhone modeli')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'iPhone modeli',
                'verbose_name_plural': 'iPhone modellari',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Taminotchi nomi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Taminotchi',
                'verbose_name_plural': 'Taminotchilar',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('condition_percentage', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Holati (%)')),
                ('status', models.CharField(choices=[('shop', "Do'konda"), ('master', 'Ustada'), ('sold', 'Sotilgan'), ('returned', 'Qaytarilgan'), ('exchanged_in', 'Almashtirishda qabul qilingan')], default='shop', max_length=15, verbose_name='Holati')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotib olingan narx')),
                ('imei_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IMEI xarajatlari')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Ta'mirlash xarajatlari")),
                ('cost_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Tan narx')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sotish narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/', verbose_name='Rasm')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('source_type', models.CharField(choices=[('supplier', 'Taminotchi'), ('client', 'Mijoz'), ('exchange', 'Almashtirish'), ('daily_client', 'Kunlik mijoz')], default='supplier', max_length=15, verbose_name='Manba turi')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mijoz ismi')),
                ('client_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mijoz telefon raqami')),
                ('exchange_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Almashtirish qiymati')),
                ('original_owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Asl egasi ismi')),
                ('original_owner_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Asl egasi telefon raqami')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('memory_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.memorysize', verbose_name='Xotira hajmi')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='shops.shop', verbose_name="Do'kon")),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.phonemodel', verbose_name='iPhone modeli')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Taminotchi')),
            ],
            options={
                'verbose_name': 'Telefon',
                'verbose_name_plural': 'Telefonlar',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Aksessuar nomi')),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Faqat raqam kiritish mumkin!')], verbose_name='Aksessuar kodi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/', verbose_name='Rasm')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tannarx')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sotish narxi')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Soni')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='shops.shop', verbose_name="Do'kon")),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Taminotchi')),
            ],
            options={
                'verbose_name': 'Aksessuar',
                'verbose_name_plural': 'Aksessuarlar',
            },
        ),
    ]
