# Generated by Django 5.2.5 on 2025-09-16 20:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Faqat raqam kiritish mumkin!')], verbose_name='Aksessuar kodi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', "IMEI 15 ta raqamdan iborat bo'lishi kerak")], verbose_name='IMEI'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['code'], name='accessory_code_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['imei'], name='phone_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['status'], name='phone_status_idx'),
        ),
    ]
