# Generated by Django 5.2.5 on 2025-09-23 18:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_phone_client_name_and_more'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accessory',
            name='accessory_code_idx',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='code',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Faqat raqam kiritish mumkin!')], verbose_name='Aksessuar kodi'),
        ),
        migrations.AlterUniqueTogether(
            name='accessory',
            unique_together={('shop', 'code')},
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['shop', 'code'], name='accessory_shop_code_idx'),
        ),
    ]
