# Generated by Django 5.2.5 on 2025-09-24 20:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_accessory_accessory_code_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tannarx'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='quantity',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Soni'),
        ),
        migrations.CreateModel(
            name='AccessoryPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Soni')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tannarx')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name="Qo'shilgan sana")),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='inventory.accessory', verbose_name='Aksessuar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
            ],
            options={
                'verbose_name': 'Aksessuar sotib olish tarixi',
                'verbose_name_plural': 'Aksessuar sotib olish tarixlari',
            },
        ),
    ]
