# Generated by Django 5.2.5 on 2025-09-25 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_accessory_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tannarx'),
        ),
    ]
