# Generated by Django 5.2.5 on 2025-09-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_accessory_purchase_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessorypurchasehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aksessuar sotib olish tarixi', 'verbose_name_plural': 'Aksessuar sotib olish tarixlari'},
        ),
    ]
