# Generated by Django 5.2.5 on 2025-09-26 22:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_accessorypurchasehistory_options'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Tannarx (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Sotish narxi (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Taminotchi'),
        ),
        migrations.AlterField(
            model_name='accessorypurchasehistory',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Tannarx (so'm)"),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Tan narx ($)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='exchange_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Almashtirish qiymati ($)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IMEI xarajatlari ($)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotib olingan narx ($)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='repair_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Ta'mirlash xarajatlari ($)"),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sotish narxi ($)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('shop', "Do'konda"), ('master', 'Ustada'), ('sold', 'Sotilgan'), ('returned', 'Qaytarilgan'), ('exchanged_in', 'Almashtirishda qabul qilingan')], db_index=True, default='shop', max_length=15, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['shop', 'status'], name='phone_shop_status_idx'),
        ),
    ]
