# Generated by Django 5.2.5 on 2025-09-27 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_accessory_purchase_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='seller',
        ),
        migrations.AlterField(
            model_name='phone',
            name='source_type',
            field=models.CharField(choices=[('supplier', 'Taminotchi'), ('external_seller', 'Tashqi sotuvchi (Diler)'), ('exchange', 'Almashtirish')], default='supplier', max_length=20, verbose_name='Manba turi'),
        ),
        migrations.CreateModel(
            name='ExternalSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tashqi sotuvchi ismi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('image', models.ImageField(blank=True, null=True, upload_to='external_sellers/', verbose_name='Rasm')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
            ],
            options={
                'verbose_name': 'Tashqi sotuvchi (Diler)',
                'verbose_name_plural': 'Tashqi sotuvchilar (Dilerlar)',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='external_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_phones', to='inventory.externalseller', verbose_name='Tashqi sotuvchi (Diler)'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
