# Generated by Django 5.2.5 on 2025-09-27 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_phone_seller_alter_phone_source_type_and_more'),
        ('sales', '0010_remove_phoneexchange_old_phone_evaluated_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='daily_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Kunlik sotuvchiga to'langan summa ($)"),
        ),
        migrations.AddField(
            model_name='phone',
            name='daily_payment_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_seller_phones', to='sales.expense', verbose_name="Bog'langan xarajat"),
        ),
        migrations.AlterField(
            model_name='phone',
            name='source_type',
            field=models.CharField(choices=[('supplier', 'Taminotchi'), ('external_seller', 'Tashqi sotuvchi (Diler)'), ('daily_seller', 'Kunlik sotuvchi'), ('exchange', 'Almashtirish')], default='supplier', max_length=20, verbose_name='Manba turi'),
        ),
        migrations.CreateModel(
            name='DailySeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kunlik sotuvchi ismi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
            ],
            options={
                'verbose_name': 'Kunlik sotuvchi',
                'verbose_name_plural': 'Kunlik sotuvchilar',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='daily_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_phones', to='inventory.dailyseller', verbose_name='Kunlik sotuvchi'),
        ),
    ]
