# Generated by Django 5.2.5 on 2025-09-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_phone_daily_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyseller',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='externalseller',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqami'),
        ),
    ]
