# Generated by Django 5.2.5 on 2025-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_dailyseller_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='note',
            field=models.TextField(blank=True, help_text="Telefon haqida qo'shimcha ma'lumot", null=True, verbose_name='Izoh'),
        ),
    ]
