# Generated by Django 5.2.5 on 2025-10-04 17:31

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_phone_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='dailyseller',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='externalseller',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='memorysize',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateField(default=datetime.date(2025, 10, 4), verbose_name='Yaratilgan sana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='imei',
            field=models.CharField(db_index=True, default=datetime.date(2025, 10, 4), max_length=20, validators=[django.core.validators.RegexValidator('^\\d{15}$', "IMEI 15 ta raqamdan iborat bo'lishi kerak")], verbose_name='IMEI'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
    ]
