# Generated by Django 5.2.5 on 2025-10-04 17:51

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_accessory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='accessorypurchasehistory',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='dailyseller',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='externalseller',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='memorysize',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Yaratilgan sana'),
        ),
    ]
