# Generated by Django 5.2.5 on 2025-10-05 04:20

import django.core.validators
import django.db.models.deletion
import inventory.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_accessory_created_at_and_more'),
        ('sales', '0015_alter_accessorysale_credit_amount_and_more'),
        ('shops', '0003_alter_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="To'lov summasi ($)")),
                ('payment_type', models.CharField(choices=[('general', "Umumiy to'lov (FIFO)"), ('specific', 'Tanlangan telefonlar')], default='general', max_length=10, verbose_name="To'lov turi")),
                ('payment_date', models.DateField(default=inventory.models.get_current_date, verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Taminotchiga to'lov",
                'verbose_name_plural': "Taminotchiga to'lovlar",
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Bu telefonga to'langan ($)")),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oldingi qarz ($)')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yangi qarz ($)')),
            ],
            options={
                'verbose_name': "To'lov tafsiloti",
                'verbose_name_plural': "To'lov tafsilotlari",
                'ordering': ['payment', 'phone'],
            },
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Taminotchi', 'verbose_name_plural': 'Taminotchilar'},
        ),
        migrations.AddField(
            model_name='phone',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bu telefon uchun qolgan qarz', max_digits=10, verbose_name="Qarz qoldig'i ($)"),
        ),
        migrations.AddField(
            model_name='phone',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bu telefonга to'langan summa", max_digits=10, verbose_name="To'langan summa ($)"),
        ),
        migrations.AddField(
            model_name='phone',
            name='payment_status',
            field=models.CharField(choices=[('paid', "To'langan"), ('debt', 'Qarzda'), ('partial', "Qisman to'langan")], db_index=True, default='paid', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taminotchiga umumiy qarz miqdori', max_digits=12, verbose_name='Umumiy qarz ($)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taminotchiga to'langan umumiy summa", max_digits=12, verbose_name="To'langan ($)"),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['payment_status'], name='phone_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['supplier', 'payment_status'], name='phone_supplier_payment_idx'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Amalga oshirgan'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.supplier', verbose_name='Taminotchi'),
        ),
        migrations.AddField(
            model_name='supplierpaymentdetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.supplierpayment', verbose_name="To'lov"),
        ),
        migrations.AddField(
            model_name='supplierpaymentdetail',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='inventory.phone', verbose_name='Telefon'),
        ),
    ]
