# Generated by Django 5.2.5 on 2025-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_supplierpayment_supplierpaymentdetail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'iPhone modeli', 'verbose_name_plural': 'iPhone modellari'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Taminotchi', 'verbose_name_plural': 'Taminotchilar'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='total_debt',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='total_paid',
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['phone_number'], name='supplier_phone_idx'),
        ),
    ]
