# Generated by Django 5.2.5 on 2025-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_phonemodel_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Taminotchi', 'verbose_name_plural': 'Taminotchilar'},
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='supplier_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='supplier_phone_idx',
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taminotchiga umumiy qarz miqdori', max_digits=12, verbose_name='Umumiy qarz ($)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taminotchiga to'langan umumiy summa", max_digits=12, verbose_name="To'langan ($)"),
        ),
    ]
