# Generated by Django 5.2.5 on 2025-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='initial_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tizimga kiritishdan oldingi qarz', max_digits=12, verbose_name="Boshlang'ich qarz ($)"),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Telefon olishlardan kelib chiqqan qarz', max_digits=12, verbose_name='Telefonlar qarzi ($)'),
        ),
    ]
