# Generated by Django 5.2.5 on 2025-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_supplier_initial_debt_alter_supplier_total_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Kassa'), ('safe', 'Seyf')], default='safe', help_text='Kassa - kunlik chiqim, Seyf - kunlik chiqim emas', max_length=10, verbose_name="To'lov manbasi"),
        ),
    ]
