# Generated by Django 5.2.5 on 2025-10-13 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_supplierpayment_payment_source'),
        ('shops', '0007_alter_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='shop',
            field=models.ForeignKey(default=1, help_text="Qaysi do'kondan to'lov amalga oshirildi", on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='shops.shop', verbose_name="Do'kon"),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['shop', 'payment_date'], name='inventory_s_shop_id_43fd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='inventory_s_supplie_addacc_idx'),
        ),
    ]
