# Generated by Django 5.2.5 on 2025-09-24 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='salesmanmonthlyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesmanmonthlyreport',
            name='salesman',
        ),
        migrations.RemoveField(
            model_name='salesmanmonthlyreport',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='yearlyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='yearlyreport',
            name='shop',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='accessories_sold_count',
            new_name='total_accessory_sales',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='exchanges_count',
            new_name='total_exchanges',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='phones_sold_count',
            new_name='total_phone_sales',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='accessory_sales_profit',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='accessory_sales_total',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='card_received',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='cash_calculation_display',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='cash_received',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='debt_amount',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='debt_payments_received',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='exchange_difference_total',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='exchange_new_phones_sold_value',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='exchange_phones_accepted_count',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='exchange_phones_accepted_value',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phone_sales_profit',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phone_sales_total',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phones_purchased_cash_paid',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phones_purchased_count',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phones_purchased_total_value',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phones_returned_count',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='phones_returned_total_value',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='net_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sof naqd (xarajatsiz)'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy karta'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy naqd'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy nasiya'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy qarz'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy savdo summasi'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy xarajatlar'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy foyda'),
        ),
        migrations.CreateModel(
            name='SellerDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Hisobot sanasi')),
                ('phone_sales_count', models.IntegerField(default=0, verbose_name='Sotilgan telefonlar soni')),
                ('accessory_sales_count', models.IntegerField(default=0, verbose_name='Sotilgan aksessuarlar soni')),
                ('exchanges_count', models.IntegerField(default=0, verbose_name='Almashtirishlar soni')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy savdo summasi')),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Yig'ilgan naqd")),
                ('card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Karta to'lovlari")),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nasiya summasi')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qarz summasi')),
                ('total_profit_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Yaratilgan foyda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_daily_reports', to='shops.shop', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Sotuvchi kunlik hisobot',
                'verbose_name_plural': 'Sotuvchi kunlik hisobotlar',
                'ordering': ['-report_date', 'seller__first_name'],
                'unique_together': {('seller', 'shop', 'report_date')},
            },
        ),
        migrations.DeleteModel(
            name='DailySalesmanReport',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.DeleteModel(
            name='SalesmanMonthlyReport',
        ),
        migrations.DeleteModel(
            name='YearlyReport',
        ),
    ]
