# Generated by Django 5.2.5 on 2025-09-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_monthlyreport_unique_together_and_more'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerdailyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sellerdailyreport',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='sellerdailyreport',
            name='shop',
        ),
        migrations.CreateModel(
            name='QuickReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_type', models.CharField(choices=[('daily', 'Kunlik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('shop', 'report_date', 'report_type')},
            },
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='SellerDailyReport',
        ),
    ]
