# Generated by Django 5.2.5 on 2025-09-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_sellerdailyreport_unique_together_and_more'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quickreport',
            options={'ordering': ['-report_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='quickreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quickreport',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quickreport',
            name='report_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='quickreport',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Kunlik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='quickreport',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reports', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='quickreport',
            index=models.Index(fields=['shop', 'report_type', 'report_date'], name='reports_qui_shop_id_b3faab_idx'),
        ),
    ]
