# Generated by Django 5.2.5 on 2025-09-29 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_dailyseller_phone_number_and_more'),
        ('reports', '0004_alter_quickreport_options_quickreport_updated_at_and_more'),
        ('sales', '0011_debt_currency_alter_accessorysale_card_amount_and_more'),
        ('shops', '0003_alter_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('phone_sale', 'Telefon sotildi'), ('exchange_income', 'Almashtirish - mijoz pul berdi'), ('daily_seller_payment', "Kunlik sotuvchiga to'lov"), ('exchange_expense', "Almashtirish - do'kon pul berdi"), ('phone_return', 'Telefon qaytarish')], max_length=30)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.phoneexchange')),
                ('related_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.phone')),
                ('related_phone_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.phonesale')),
                ('related_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.phonereturn')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'transaction_date'], name='reports_cas_shop_id_416ac1_idx'), models.Index(fields=['transaction_type'], name='reports_cas_transac_82418c_idx')],
            },
        ),
    ]
