# Generated by Django 5.2.5 on 2025-09-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_cashflowtransaction'),
        ('sales', '0011_debt_currency_alter_accessorysale_card_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowtransaction',
            name='amount_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cashflowtransaction',
            name='related_accessory_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.accessorysale'),
        ),
        migrations.AddField(
            model_name='cashflowtransaction',
            name='related_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.expense'),
        ),
        migrations.AlterField(
            model_name='cashflowtransaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashflowtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('phone_sale', 'Telefon sotildi'), ('accessory_sale', 'Aksessuar sotildi'), ('exchange_income', 'Almashtirish - mijoz pul berdi'), ('daily_seller_payment', "Kunlik sotuvchiga to'lov"), ('exchange_expense', "Almashtirish - do'kon pul berdi"), ('phone_return', 'Telefon qaytarish'), ('daily_expense', 'Kunlik harajat'), ('exchange_equal', 'Teng almashtirish')], max_length=30),
        ),
    ]
