# Generated by Django 5.2.5 on 2025-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_cashflowtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('phone_sale', 'Telefon sotildi'), ('accessory_sale', 'Aksessuar sotildi'), ('exchange_income', 'Almashtirish - mijoz pul berdi'), ('daily_seller_payment', "Kunlik sotuvchiga to'lov"), ('exchange_expense', "Almashtirish - do'kon pul berdi"), ('phone_return', 'Telefon qaytarish'), ('daily_expense', 'Kunlik harajat'), ('exchange_old_phone_value', 'Almashtirish - olingan telefon qiymati'), ('exchange_equal', 'Teng almashtirish')], max_length=30),
        ),
    ]
