# Generated by Django 5.2.5 on 2025-10-09 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_supplierpayment_payment_source'),
        ('reports', '0009_alter_cashflowtransaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowtransaction',
            name='related_supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplierpayment', verbose_name="Bog'liq to'lov"),
        ),
        migrations.AlterField(
            model_name='cashflowtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('phone_sale', 'Telefon sotildi'), ('accessory_sale', 'Aksessuar sotildi'), ('exchange_income', 'Almashtirish - mijoz pul berdi'), ('daily_seller_payment', "Kunlik sotuvchiga to'lov"), ('exchange_expense', "Almashtirish - do'kon pul berdi"), ('phone_return', 'Telefon qaytarish'), ('daily_expense', 'Kunlik harajat'), ('exchange_old_phone_value', 'Almashtirish - olingan telefon qiymati'), ('supplier_payment_cash', "💵 Taminotchiga to'lov (Kassa)"), ('exchange_equal', 'Teng almashtirish')], max_length=30),
        ),
    ]
