# Generated by Django 5.2.5 on 2025-09-16 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Do'kon nomi")),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('owner', models.ForeignKey(limit_choices_to={'userprofile__role': 'boss'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Do'kon egasi")),
            ],
            options={
                'verbose_name': "Do'kon",
                'verbose_name_plural': "Do'konlar",
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('image', models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Mijoz rasmi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name="Qo'shilgan sana")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'unique_together': {('shop', 'phone_number')},
            },
        ),
    ]
