# Generated by Django 5.2.5 on 2025-09-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqami'),
        ),
    ]
