# Generated by Django 5.2.5 on 2025-10-07 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kuni"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqami'),
        ),
    ]
