# Generated by Django 5.2.5 on 2025-10-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, verbose_name='Telefon raqami'),
        ),
    ]
