# Generated by Django 5.2.5 on 2025-09-16 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessorySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Soni')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Umumiy narx')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Nasiya')], max_length=10, verbose_name="To'lov usuli")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'langan summa (naqd/karta)")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name="Nasiya summasi (agar nasiya bo'lsa)")),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sotish sanasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.accessory', verbose_name='Aksessuar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_sales', to='shops.customer', verbose_name='Mijoz')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Aksessuar sotish',
                'verbose_name_plural': 'Aksessuar sotuvlari',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('customer_to_seller', 'Mijoz → Sotuvchi'), ('seller_to_boss', 'Sotuvchi → Boshliq'), ('boss_to_master', 'Boshliq → Usta')], max_length=20, verbose_name='Qarz turi')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Qarz summasi (max 500$)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="To'langan summa")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='active', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_debts', to=settings.AUTH_USER_MODEL, verbose_name='Qarz bergan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='shops.customer', verbose_name='Qarz olgan (Mijoz)')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_debts', to=settings.AUTH_USER_MODEL, verbose_name='Qarz olgan (Foydalanuvchi)')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="To'lov summasi")),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.debt', verbose_name='Qarz')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan')),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Xarajat nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Summa')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Xarajat sanasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='shops.shop', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='PhoneExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_phone_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Yangi telefon narxi')),
                ('old_phone_imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='Eski IMEI')),
                ('old_phone_evaluated_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baholangan narxi')),
                ('price_difference', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Narx farqi')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Nasiya')], max_length=10, verbose_name="To'lov usuli")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'langan summa")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Qarz summasi')),
                ('exchange_date', models.DateField(default=django.utils.timezone.now, verbose_name='Almashtirish sanasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_old_phone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_exchange', to='inventory.phone', verbose_name='Yaratilgan eski telefon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_exchanges', to='shops.customer', verbose_name='Mijoz')),
                ('new_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_new', to='inventory.phone', verbose_name='Yangi telefon')),
                ('old_phone_memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.memorysize', verbose_name='Eski xotira')),
                ('old_phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.phonemodel', verbose_name='Eski model')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Telefon almashtirish',
                'verbose_name_plural': 'Telefon almashtirishlar',
                'ordering': ['-exchange_date'],
            },
        ),
        migrations.CreateModel(
            name='PhoneSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Sotish narxi')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Nasiya')], max_length=10, verbose_name="To'lov usuli")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="To'langan summa (naqd/karta)")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name="Nasiya summasi (agar nasiya bo'lsa)")),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sotish sanasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_sales', to='shops.customer', verbose_name='Mijoz')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.phone', verbose_name='Telefon')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': 'Telefon sotish',
                'verbose_name_plural': 'Telefon sotuvlari',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='PhoneReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qaytarilgan summa')),
                ('return_date', models.DateField(default=django.utils.timezone.now, verbose_name='Qaytarilgan sana')),
                ('reason', models.TextField(verbose_name='Qaytarish sababi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qaytarishni amalga oshirgan')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.phone', verbose_name='Qaytarilgan telefon')),
                ('phone_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_return', to='sales.phonesale', verbose_name="Bog'langan telefon sotish")),
            ],
            options={
                'verbose_name': 'Telefon qaytarish',
                'verbose_name_plural': 'Telefon qaytarishlar',
                'ordering': ['-return_date'],
            },
        ),
    ]
