# Generated by Django 5.2.5 on 2025-09-16 19:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorysale',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='accessorysale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='phoneexchange',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='phoneexchange',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='phonesale',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='phonesale',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='accessorysale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karta'),
        ),
        migrations.AddField(
            model_name='accessorysale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Naqd'),
        ),
        migrations.AddField(
            model_name='accessorysale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nasiya savdo'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karta'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Naqd'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nasiya savdo'),
        ),
        migrations.AddField(
            model_name='phonesale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karta'),
        ),
        migrations.AddField(
            model_name='phonesale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Naqd'),
        ),
        migrations.AddField(
            model_name='phonesale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nasiya savdo'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Qarz (max 500$)'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Qarz daftar (max 500$)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Umumiy sotish narxi'),
        ),
    ]
