# Generated by Django 5.2.5 on 2025-09-17 00:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_accessory_code_alter_phone_imei_and_more'),
        ('sales', '0002_remove_accessorysale_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneexchange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phone_exchanges', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='exchange_type',
            field=models.CharField(choices=[('customer_pays', "Mijoz qo'shimcha pul to'laydi"), ('shop_pays', "Do'kon qo'shimcha pul to'laydi"), ('equal', 'Teng qiymatda almashtirish')], default=1, editable=False, max_length=20, verbose_name='Almashtirish turi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_condition_percentage',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Eski telefon holati (%)'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_image',
            field=models.ImageField(blank=True, null=True, upload_to='phones/exchanged/', verbose_name='Eski telefon rasmi'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_imei_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Eski telefon IMEI xarajati'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Eski telefon sotib olingan narxi'),
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_repair_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Eski telefon ta'mirlash xarajati"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Karta to'lov"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Naqd to'lov"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nasiya to'lov"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name="Qarz to'lov (max 500$)"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='exchange_date',
            field=models.DateField(verbose_name='Almashtirish sanasi'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_evaluated_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eski telefon baholangan narxi (sotish narxi)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_imei',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', "IMEI 15 ta raqamdan iborat bo'lishi kerak")], verbose_name='Eski telefon IMEI'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.memorysize', verbose_name='Eski telefon xotirasi'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.phonemodel', verbose_name='Eski telefon modeli'),
        ),
    ]
