# Generated by Django 5.2.5 on 2025-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_phoneexchange_created_by_phoneexchange_exchange_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneexchange',
            name='exchange_type',
            field=models.CharField(choices=[('customer_pays', "Mijoz qo'shimcha pul to'laydi"), ('shop_pays', "Do'kon qo'shimcha pul to'laydi"), ('equal', 'Teng qiymatda almashtirish')], max_length=20, verbose_name='Almashtirish turi'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Narx farqi (avtomatik hisoblanadi)'),
        ),
    ]
