# Generated by Django 5.2.5 on 2025-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_phoneexchange_exchange_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneexchange',
            name='customer',
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='customer_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Mijoz ismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='customer_phone_number',
            field=models.CharField(default=1, max_length=15, verbose_name='Mijoz telefon raqami'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Narx farqi'),
        ),
    ]
