# Generated by Django 5.2.5 on 2025-09-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_phoneexchange_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonereturn',
            name='phone',
        ),
    ]
