# Generated by Django 5.2.5 on 2025-09-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_accessory_code_alter_phone_imei_and_more'),
        ('sales', '0006_remove_phonereturn_phone'),
        ('shops', '0002_alter_customer_unique_together_remove_customer_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneexchange',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_exchanges', to='shops.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phonesale', to='inventory.phone', verbose_name='Telefon'),
        ),
    ]
