# Generated by Django 5.2.5 on 2025-09-21 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_phoneexchange_customer_alter_phonesale_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_evaluated_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eski telefon baholangan narxi'),
        ),
    ]
