# Generated by Django 5.2.5 on 2025-09-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_phoneexchange_old_phone_evaluated_price'),
        ('services', '0009_remove_master_user_remove_masterservice_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='services.master', verbose_name='Qarz olgan (Usta)'),
        ),
    ]
