# Generated by Django 5.2.5 on 2025-09-24 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_debt_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneexchange',
            name='old_phone_evaluated_price',
        ),
        migrations.RemoveField(
            model_name='phoneexchange',
            name='old_phone_purchase_price',
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_accepted_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eski telefon qabul qilingan narx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneexchange',
            name='old_phone_future_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Eski telefon kelajakdagi sotish narxi'),
        ),
    ]
