# Generated by Django 5.2.5 on 2025-09-28 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_phoneexchange_old_phone_evaluated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar'), ('UZS', "So'm")], default='USD', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Karta (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Naqd (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nasiya savdo (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name="Qarz (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name="Umumiy narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="Birlik narxi (so'm)"),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Qarz summasi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name="To'lov summasi"),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Summa (so'm)"),
        ),
    ]
