# Generated by Django 5.2.5 on 2025-09-30 18:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_dailyseller_phone_number_and_more'),
        ('sales', '0011_debt_currency_alter_accessorysale_card_amount_and_more'),
        ('services', '0009_remove_master_user_remove_masterservice_debt'),
        ('shops', '0003_alter_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneexchange',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karta ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Naqd ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phone_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nasiya ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Qarz (max 500$)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='new_phone_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Yangi telefon narxi ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_accepted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eski telefon qabul narxi ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_future_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kelajakdagi sotish narxi ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_imei_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IMEI xarajati ($)'),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='old_phone_repair_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Ta'mirlash xarajati ($)"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Narx farqi ($)'),
        ),
        migrations.AlterField(
            model_name='phonereturn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='phonereturn',
            name='phone_sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_return', to='sales.phonesale', verbose_name='Telefon sotish'),
        ),
        migrations.AlterField(
            model_name='phonereturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qaytarilgan summa ($)'),
        ),
        migrations.AlterField(
            model_name='phonereturn',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Qaytarish sanasi'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karta ($)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Naqd ($)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nasiya ($)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Qarz (max 500$)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Sotish narxi ($)'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['status', 'currency'], name='sales_debt_status_ae7375_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['creditor', 'status'], name='sales_debt_credito_b3f423_idx'),
        ),
        migrations.AddIndex(
            model_name='phonesale',
            index=models.Index(fields=['sale_date', 'salesman'], name='sales_phone_sale_da_f15c15_idx'),
        ),
    ]
