# Generated by Django 5.2.5 on 2025-10-04 14:03

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_phone_note'),
        ('sales', '0012_alter_phoneexchange_card_amount_and_more'),
        ('shops', '0003_alter_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorysale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='exchange_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Almashtirish sanasi'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='phoneexchange',
            index=models.Index(fields=['exchange_date', 'salesman'], name='sales_phone_exchang_a0e95b_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneexchange',
            index=models.Index(fields=['customer', 'exchange_type'], name='sales_phone_custome_46ac7b_idx'),
        ),
    ]
