# Generated by Django 5.2.5 on 2025-10-04 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_accessorysale_card_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phoneexchange',
            name='sales_phone_exchang_a0e95b_idx',
        ),
        migrations.RemoveIndex(
            model_name='phoneexchange',
            name='sales_phone_custome_46ac7b_idx',
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Karta (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Naqd (so'm)"),
        ),
        migrations.AlterField(
            model_name='accessorysale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nasiya savdo (so'm)"),
        ),
        migrations.AlterField(
            model_name='phoneexchange',
            name='exchange_date',
            field=models.DateField(verbose_name='Almashtirish sanasi'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karta ($)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Naqd ($)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nasiya ($)'),
        ),
    ]
