# Generated by Django 5.2.5 on 2025-10-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_supplier_options_and_more'),
        ('sales', '0015_alter_accessorysale_credit_amount_and_more'),
        ('shops', '0003_alter_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonesale',
            options={'ordering': ['-sale_date', '-id'], 'verbose_name': 'Telefon sotish', 'verbose_name_plural': 'Telefon sotuvlari'},
        ),
        migrations.AddField(
            model_name='phonesale',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Qaytarilganmi?'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_sales', to='inventory.phone', verbose_name='Telefon'),
        ),
        migrations.AddIndex(
            model_name='phonesale',
            index=models.Index(fields=['phone', 'is_returned'], name='sales_phone_phone_i_20c6e9_idx'),
        ),
    ]
