# Generated by Django 5.2.5 on 2025-10-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_phonesale_options_phonesale_is_returned_and_more'),
    ]

    operations = [
    ]
