# Generated by Django 5.2.5 on 2025-10-16 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_phoneexchange_debt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneexchange',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Qarz (max 500$)'),
        ),
        migrations.AlterField(
            model_name='phonesale',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Qarz (max 500$)'),
        ),
    ]
